### ISSUE TITLE
Error when querying ELBs

### ISSUE THREAD

**Issue by sfrizzle** [9rnt/poro#1]
°° Searching for exposed ELBs °°
Traceback (most recent call last):
  File "poro.py", line 24, in <module>
    elbs=getELB()
  File "/home/cloudshell-user/poro/modules/elb.py", line 23, in getELB
    publicLoadbalancers.append([elb['LoadBalancerArn'],[elb['DNSName'],elb['SecurityGroups']]])
KeyError: 'SecurityGroups'

Script terminates when error is encountered.

**Comment by 9rnt** [comment]
Hello @sfrizzle 
Can you please provide the configuration of the ELB that returned that error (I added more debugging info to understand what is causing this issue)

**Comment by 9rnt** [comment]
closing the issue since there has been no update for more than 30 days.
